CHANNEL = "#bugbyte-ita"
BOTNAME = "CovidBot"
IRC_SERVER_ADDRESS = "irc.freenode.net"
HTTP_REQUEST_TIMEOUT = 5 # timeout in seconds

NEWSAPI_KEY = ''
OPENWEATHER_KEY = ''
YOUTUBE_KEY = ''
META_API_AUTH = ''
CLEVERBOT_KEY = ''
WOLFRAM_KEY = ''
SEARCH_ENGINE = ''
TELEGRAM_TOKEN = ''

ENABLE_MINIFLUX = False
MINIFLUX_URL = ''
MINIFLUX_USER = ''
MINIFLUX_PSW = ''

CHESSENGINE_PATH = ''