CHANNEL = "#bugbyte-ita"
BOTNAME = "CovidBot"
IRC_SERVER_ADDRESS = "irc.freenode.net"
HTTP_REQUEST_TIMEOUT = 20 # timeout in seconds

NEWSAPI_KEY = ''
OPENWEATHER_KEY = ''
YOUTUBE_KEY = ''
META_API_AUTH = ''
WOLFRAM_KEY = ''
SEARCH_ENGINE = ''
TELEGRAM_TOKEN = ''

USE_LOCAL_CHATBOT = False
CLEVERBOT_KEY = ''
CHATBOT_KEY = ''
AUTO_SPEAK = False
AUTO_SPEAK_INTERVAL = 60

ENABLE_MINIFLUX = False
MINIFLUX_URL = ''
MINIFLUX_USER = ''
MINIFLUX_PSW = ''

CHESSENGINE_PATH = ''